spark.app.name EC528ModernFixed
spark.executor.defaultJavaOptions -Dfeature.alpha=false
spark.executor.extraJavaOptions -Dregion=us-east-1 -Dtrace=true
spark.hadoop.yarn.resourcemanager.address rm:8032
spark.yarn.appMasterEnv.PYSPARK_PYTHON /opt/venv/bin/python
spark.executorEnv.PYSPARK_PYTHON /opt/venv/bin/python
spark.submit.deployMode cluster
