spark.app.name EC528ModernBuggy
spark.executor.defaultJavaOptions -Dregion=us-east-1 -Dfeature.alpha=false
spark.executor.extraJavaOptions -Dregion=us-west-2 -Dtrace=true
yarn.resourcemanager.address rm:8032
spark.submit.deployMode cluster
